server:
  port: 5001

spring:
  jpa:
    # Postgres
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    # MySQL
    # database-platform: org.hibernate.dialect.MySQL8Dialect
    # show-sql: true
    # hibernate:
    # ddl-auto: update
  datasource:
    # Postgres
    url: jdbc:postgresql://localhost:5432/bankAccount
    username: postgres
    password: example
    # MySQL
    # url: jdbc:mysql://localhost:3306/bankAccount?createDatabaseIfNotExist=true
    # username: root
    # password: example
  kafka:
    listener:
      ack-mode: manual_immediate
    consumer:
      bootstrap-servers: localhost:9092
      group-id: bankaccConsumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: '*'
