version: '3.7'

services:
  mongodb:
    image: "mongo:4.4"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"

  mysql:
    image: "mysql:8.0.33"
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=example

  kafka:
    image: bitnami/kafka:3.2.3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes

  postgres:
    image: "postgres:15"
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=example

volumes:
  kafka_data:
    driver: local
  mongodb_data:
    driver: local
  mysql_data:
    driver: local
  postgresql_data:
    driver: local
